// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlydlQOFHzkjREAR2A-atp9pj99IV98U0',
    appId: '1:522297217860:android:b7252e78123fdc62d3bd11',
    messagingSenderId: '522297217860',
    projectId: 'e-kentongan-ac811',
    storageBucket: 'e-kentongan-ac811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDez3HVEo1W20R09oLVe7UiaoeK3EcyUPM',
    appId: '1:522297217860:ios:51f3158e2cf02e72d3bd11',
    messagingSenderId: '522297217860',
    projectId: 'e-kentongan-ac811',
    storageBucket: 'e-kentongan-ac811.firebasestorage.app',
    iosBundleId: 'com.penacode.ekentongan.eKentongan',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgf0t50VPnsf7vcacopSy4qJbwC2SAuVU',
    appId: '1:522297217860:web:710f94a8513d1f6ad3bd11',
    messagingSenderId: '522297217860',
    projectId: 'e-kentongan-ac811',
    authDomain: 'e-kentongan-ac811.firebaseapp.com',
    storageBucket: 'e-kentongan-ac811.firebasestorage.app',
    measurementId: 'G-EMMXN64LQB',
  );

}